-- Supabase Schema for DA NANG GREEN
-- Run this in your Supabase SQL Editor

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL, -- 'admin', 'district_manager', 'ward_manager', 'school_manager', 'department_manager', 'environment_department', 'citizen'
  area TEXT, -- e.g., 'Hải Châu', 'Sơn Trà', 'Hòa Vang', 'All'
  organizationName TEXT,
  email TEXT,
  phone TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Reports Table
CREATE TABLE IF NOT EXISTS reports (
  id TEXT PRIMARY KEY, -- Using UUID or custom ID from frontend
  mediaUrl TEXT,
  mediaType TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  userDescription TEXT,
  issueType TEXT,
  description TEXT,
  priority TEXT,
  solution TEXT,
  isIssuePresent SMALLINT DEFAULT 0, -- 0 for false, 1 for true
  status TEXT, -- 'Báo cáo mới', 'Đang xử lý', 'Đã xử lý'
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  area TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId BIGINT REFERENCES users(id),
  reportId TEXT REFERENCES reports(id),
  message TEXT,
  type TEXT, -- 'new_report', 'status_update', 'emergency'
  isRead SMALLINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Orders Table (New)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId BIGINT REFERENCES users(id),
  productName TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'shipped', 'delivered'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create Policies (Simplified for demo, adjust for production)
-- Allow all authenticated users to read reports
CREATE POLICY "Allow public read access on reports" ON reports FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on reports" ON reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on reports" ON reports FOR UPDATE USING (true);

-- Allow users to read their own notifications
CREATE POLICY "Allow users to read their own notifications" ON notifications FOR SELECT USING (true);
CREATE POLICY "Allow users to update their own notifications" ON notifications FOR UPDATE USING (true);

-- Allow users to manage their own orders
CREATE POLICY "Allow users to manage their own orders" ON orders FOR ALL USING (true);

-- Allow public read on users (for login check)
CREATE POLICY "Allow public read on users" ON users FOR SELECT USING (true);
CREATE POLICY "Allow public insert on users" ON users FOR INSERT WITH CHECK (true);

-- Seed initial admin user (password is '123456' hashed with bcrypt)
-- Note: In a real app, you'd use Supabase Auth, but this app uses a custom JWT flow over Supabase tables.
INSERT INTO users (username, password, role, area, organizationName)
VALUES 
('admin@dananggreen.vn', '$2a$10$7pXp.vXyX.vXyX.vXyX.vO', 'environment_department', 'All', 'Hệ thống Đà Nẵng Green'),
('quanly@dananggreen.vn', '$2a$10$7pXp.vXyX.vXyX.vXyX.vO', 'department_manager', 'Hải Châu', 'Ban Quản lý Môi trường')
ON CONFLICT (username) DO NOTHING;
